name: 'clean_star'
version: '1.0.0'

profile: 'clean_star'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  clean_star:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: view
      +schema: int
    marts:
      dimensions:
        +materialized: table
        +schema: mart
      facts:
        +materialized: table
        +schema: mart
